services:

  flex-stn1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flex-stn1
    ports:
      - "5051:5051/udp"
    restart: unless-stopped
    environment:
      - UDPPORT=5051
      - FLEXIP=192.168.88.51
      - FLEXPORT=4992
      - STN=stn1
      - MQTT_HOST=192.168.88.10
      - MQTT_PORT=1883
    logging:
      options:
        max-size: "10m"

  flex-stn2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flex-stn2
    ports:
      - "5052:5052/udp"
    restart: unless-stopped
    environment:
      - UDPPORT=5052
      - FLEXIP=192.168.88.52
      - FLEXPORT=4992
      - STN=stn2
      - MQTT_HOST=192.168.88.10
      - MQTT_PORT=1883
    logging:
      options:
        max-size: "10m"